# _config.yml
title: Scopes Coffee
url: "https://ryivins.github.io"   
baseurl: "/Scopes-Coffee"          
markdown: kramdown
# permalink: pretty               
# theme: minima                  
plugins:
  - jekyll-feed
